### ISSUE TITLE
Yellow background page after login

### ISSUE THREAD

**Issue by Opswatch** [alexisbouchez/proustai#1]
Issue: Getting a yellow background page after login

OS: Ubuntu running docker on wsl2 

Node version: v20.11.1

Npm version: 10.5.0

Restarted both containers, same result, nothing unusual in the postgres logs or the main http server terminal window.

**Comment by alexisbouchez** [comment]
Thanks for reporting, will try to reproduce tomorrow

**Comment by alexisbouchez** [comment]
fixed in the latest commit https://github.com/alexisbouchez/proustai/commit/a3a811ba5910888629e5af6c0d8fa07d2342bb71
